PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT (xsd:double((?value1
				   +?value2
				   +?value3)) AS ?metricResult)
WHERE 
{
	?order :hasMetricCO_28  ?value1 .
	?order :hasMetricCO_29  ?value2 .
	?order :hasMetricCO_30  ?value3 .
}
