PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT (xsd:double((?value1 + ?value2 + ?value3)) AS ?metricResult)
WHERE 
{
	?order :hasMetricAM_6  ?value1 .
	?order :hasMetricAM_7  ?value2 .
	?order :hasMetricAM_8  ?value3 .
}
