PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT (xsd:double((?value1+?value2)/2) AS ?metricResult)
WHERE 
{
	?order :hasMetricRL_32 ?value1 .
	?order :hasMetricRL_34 ?value2 .
}
