PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT (xsd:double((?value1+?value2+?value3+?value4)/4) AS ?metricResult)
WHERE 
{
	?order :hasMetricRL_31 ?value1 .
	?order :hasMetricRL_43 ?value2 .
	?order :hasMetricRL_45 ?value1 .
	?order :hasMetricRL_50 ?value2 .
}
