PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

# RL.2.4 Perfect Condition

SELECT (xsd:double(( ?rl12 + ?rl24 + ?rl41 + ?rl42 + ?rl55 ) / 5) AS ?metricResult)
WHERE 
{
	?order :hasMetricRL_12 ?rl12 . # % Of Faultless Installations
	?order :hasMetricRL_24 ?rl24 . # % Orders/lines received damage free
	?order :hasMetricRL_41 ?rl41 . # % of orders which is delivered without damage.
	?order :hasMetricRL_42 ?rl42 . # % of orders which is delivered without defect.
	?order :hasMetricRL_55 ?rl55 . # Number of returns within the warranty period.
}
