PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT (xsd:double((?value1+?value2+?value3+?value4+?value5)/5) AS ?metricResult)
WHERE 
{
	?order :hasMetricRL_12 ?value1 .
	?order :hasMetricRL_24 ?value2 .
	?order :hasMetricRL_41 ?value3 .
	?order :hasMetricRL_42 ?value4 .
	?order :hasMetricRL_55 ?value5 .
}
